### ISSUE TITLE
Two copies of the DLL in the ZIP

### ISSUE THREAD

**Issue by HebaruSan** [cmac994/KerBalloons#1]
One here:

![image](https://user-images.githubusercontent.com/1559108/103649777-acb6a500-4f24-11eb-831c-d8ea84ce88f0.png)

And one here:

![image](https://user-images.githubusercontent.com/1559108/103649832-bb04c100-4f24-11eb-91b3-fc614d338fd9.png)

Suspiciously, they have different timestamps, so there's a risk that one of them isn't the file you meant to pack.

Noticed while reviewing KSP-CKAN/NetKAN#8296.

**Comment by cmac994** [comment]
Thank you for bringing this to my attention. I've removed the old .dll file from the Plugins/ directory and reuploaded the zip file, which now contains only one DLL.
